import type { WishItem } from "../types";

const DAY_MS = 24 * 60 * 60 * 1000;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS).toISOString();

/**
 * 최초 실행 시 화면을 채우기 위한 예시 데이터.
 * 실제 등록이 시작되면 localStorage 값이 이 목록을 대체한다.
 */
export const DUMMY_ITEMS: WishItem[] = [
  {
    id: "seed-1",
    url: "https://example.com/earbuds",
    name: "노이즈 캔슬링 무선 이어폰",
    price: 189000,
    category: "전자기기",
    reason: "출퇴근 지하철이 시끄러워서 집중이 안 됨. 통화 품질도 개선하고 싶다.",
    deliberationDays: 7,
    createdAt: daysAgo(9),
    status: "deliberating",
    reDeliberationCount: 0,
  },
  {
    id: "seed-2",
    url: "https://example.com/cardigan",
    name: "울 니트 가디건",
    price: 78000,
    category: "패션",
    reason: "환절기에 걸칠 옷이 마땅치 않다. 색이 예뻐서 눈에 계속 밟힘.",
    deliberationDays: 3,
    createdAt: daysAgo(5),
    status: "deliberating",
    reDeliberationCount: 1,
  },
  {
    id: "seed-3",
    url: "https://example.com/diffuser",
    name: "우드 아로마 디퓨저",
    price: 42000,
    category: "리빙",
    reason: "방 냄새가 신경 쓰인다. 무드등 겸용이라 하나로 두 가지 해결.",
    deliberationDays: 5,
    createdAt: daysAgo(1),
    status: "deliberating",
    reDeliberationCount: 0,
  },
  {
    id: "seed-4",
    url: "https://example.com/keyboard",
    name: "무선 기계식 키보드 (갈축)",
    price: 135000,
    category: "취미",
    reason: "지금 쓰는 키보드 타건감이 별로다. 재택근무 시간이 길어서 투자할 만하다.",
    deliberationDays: 7,
    createdAt: daysAgo(5),
    status: "deliberating",
    reDeliberationCount: 1,
  },
  {
    id: "seed-5",
    url: "https://example.com/runningshoes",
    name: "경량 러닝화",
    price: 119000,
    category: "취미",
    reason: "러닝 3개월째 지속 중. 발목 통증 때문에 쿠션 좋은 신발이 필요.",
    deliberationDays: 5,
    createdAt: daysAgo(14),
    status: "decided",
    reDeliberationCount: 0,
    decidedAt: daysAgo(8),
    decisionReason: "숙려 후에도 필요성이 분명했고, 러닝 습관 유지에 도움이 됨.",
  },
  {
    id: "seed-6",
    url: "https://example.com/tumbler",
    name: "보온 텀블러 500ml",
    price: 29000,
    category: "리빙",
    reason: "카페 일회용 컵 줄이고 싶다.",
    deliberationDays: 3,
    createdAt: daysAgo(20),
    status: "decided",
    reDeliberationCount: 0,
    decidedAt: daysAgo(17),
    decisionReason: "가격 부담이 적고 매일 쓸 물건이라 결정.",
  },
  {
    id: "seed-7",
    url: "https://example.com/tablet",
    name: "10인치 태블릿 (256GB)",
    price: 640000,
    category: "전자기기",
    reason: "영상 보고 필기용으로 쓰고 싶다.",
    deliberationDays: 7,
    createdAt: daysAgo(25),
    status: "abandoned",
    reDeliberationCount: 2,
    decidedAt: daysAgo(15),
    decisionReason: "결국 노트북과 폰으로 대부분 해결됨. 거치용도로 쓰기엔 비쌈.",
  },
  {
    // 숙려 종료 후 38일째 방치 → 앱 로드 시 sweepAutoAbandon이 자동 퇴소 처리
    id: "seed-8",
    url: "https://example.com/backpack",
    name: "가죽 백팩",
    price: 210000,
    category: "패션",
    reason: "출근용 가방이 낡았다. 오래 쓸 거라 좋은 걸로 사고 싶다.",
    deliberationDays: 7,
    createdAt: daysAgo(45),
    status: "deliberating",
    reDeliberationCount: 0,
  },
];
